DEFAULT_PLAN = [
    # ── Week 0: Orientation Week ──────────────────────────────────────────────

    # Day 0
    {"day": 0, "week": "Week 0: Orientation Week", "time_window": "6:00 PM – 2:00 AM", "duration": 1.0,
     "title": "Confirm hardware/software readiness, VIP access needs, welcome material, onboarding docs",
     "category": "LEADS", "sort": 1},

    # Day 1
    {"day": 1, "week": "Week 0: Orientation Week", "time_window": "6:00 PM – 2:00 AM", "duration": 8.0,
     "title": "Orientation at INC",
     "category": "GENERAL", "sort": 1},

    # Day 2
    {"day": 2, "week": "Week 0: Orientation Week", "time_window": "6:00 PM – 7:00 PM", "duration": 1.0,
     "title": "Hardware/software check, welcome email, training expectations, internal policy, SOC2 onboarding",
     "category": "LEADS", "sort": 1},
    {"day": 2, "week": "Week 0: Orientation Week", "time_window": "7:00 PM – 11:00 PM", "duration": 4.0,
     "title": "Orientation at AMIE",
     "category": "GENERAL", "sort": 2},
    {"day": 2, "week": "Week 0: Orientation Week", "time_window": "11:00 PM – 12:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 3},
    {"day": 2, "week": "Week 0: Orientation Week", "time_window": "12:00 AM – 3:00 AM", "duration": 3.0,
     "title": "Orientation at AMIE continued / independent onboarding review",
     "category": "GENERAL", "sort": 4},

    # Day 3
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "6:00 PM – 7:00 PM", "duration": 1.0,
     "title": "LMS training / onboarding self-study",
     "category": "GENERAL", "sort": 1},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "7:00 PM – 7:30 PM", "duration": 0.5,
     "title": "Issue VIP credentials and submit IT access ticket",
     "category": "LEADS", "sort": 2},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "7:30 PM – 8:00 PM", "duration": 0.5,
     "title": "Department overview and training expectations",
     "category": "TRAINER", "sort": 3},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "8:00 PM – 10:00 PM", "duration": 2.0,
     "title": "Completing LMS — Part 1",
     "category": "GENERAL", "sort": 4},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "10:00 PM – 11:00 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "11:00 PM – 12:00 AM", "duration": 1.0,
     "title": "Completing LMS — Part 2",
     "category": "GENERAL", "sort": 6},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Workflow Introduction / Applications",
     "category": "TRAINER", "sort": 7},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Documentation Standards / Work Instruction Review",
     "category": "TRAINER", "sort": 8},
    {"day": 3, "week": "Week 0: Orientation Week", "time_window": "2:00 AM – 3:00 AM", "duration": 1.0,
     "title": "Independent review: LMS completion, workflow notes, and WI review action items",
     "category": "ASSIGNMENT", "sort": 9},

    # Day 4
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "6:00 PM – 7:00 PM", "duration": 1.0,
     "title": "LMS / prior-day recap",
     "category": "GENERAL", "sort": 1},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "7:00 PM – 7:30 PM", "duration": 0.5,
     "title": "Trainer touchpoint, expectations, questions, daily plan",
     "category": "TRAINER", "sort": 2},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "7:30 PM – 10:30 PM", "duration": 3.0,
     "title": "Segmentation Breakdown / Anatomy",
     "category": "TRAINER", "sort": 3},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "10:30 PM – 11:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "11:30 PM – 1:30 AM", "duration": 2.0,
     "title": "Landmarking of Joint",
     "category": "TRAINER", "sort": 5},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Implant Placement introduction / trainer wrap-up",
     "category": "TRAINER", "sort": 6},
    {"day": 4, "week": "Week 0: Orientation Week", "time_window": "2:00 AM – 3:00 AM", "duration": 1.0,
     "title": "Independent practice: Implant Placement review and notes",
     "category": "ASSIGNMENT", "sort": 7},

    # ── Week 1: Foundations of VIP ────────────────────────────────────────────

    # Day 5
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Training expectations presentation / meeting",
     "category": "TRAINER", "sort": 2},
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "7:00 PM – 8:00 PM", "duration": 1.0,
     "title": "Trainer follow-along: Case 1A — SUCCESS",
     "category": "TRAINER", "sort": 3},
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "8:00 PM – 12:00 AM", "duration": 4.0,
     "title": "Plan cases 1A–2A",
     "category": "ASSIGNMENT", "sort": 4},
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 5, "week": "Week 1: Foundations of VIP", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 6},

    # Day 6
    {"day": 6, "week": "Week 1: Foundations of VIP", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 6, "week": "Week 1: Foundations of VIP", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 3A — SUCCESS",
     "category": "GENERAL", "sort": 2},
    {"day": 6, "week": "Week 1: Foundations of VIP", "time_window": "7:00 PM – 12:00 AM", "duration": 5.0,
     "title": "Plan cases 3A–4A",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 6, "week": "Week 1: Foundations of VIP", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 6, "week": "Week 1: Foundations of VIP", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 5},

    # Day 7
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 5A — OV Adjusted",
     "category": "GENERAL", "sort": 2},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "7:00 PM – 10:00 PM", "duration": 3.0,
     "title": "Plan cases 5A–6A",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "10:00 PM – 11:00 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "11:00 PM – 12:00 AM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 5},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Trainer follow-along: Case 7A — Rejection",
     "category": "TRAINER", "sort": 6},
    {"day": 7, "week": "Week 1: Foundations of VIP", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Plan cases 7A–8A",
     "category": "ASSIGNMENT", "sort": 7},

    # Day 8
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Trainer follow-along: Case 9A — Rejection",
     "category": "TRAINER", "sort": 2},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "7:00 PM – 7:30 PM", "duration": 0.5,
     "title": "Plan cases 9A–11A",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "7:30 PM – 8:00 PM", "duration": 0.5,
     "title": "Quick review / feedback / WI check",
     "category": "TRAINER", "sort": 4},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "8:00 PM – 9:00 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "9:00 PM – 9:30 PM", "duration": 0.5,
     "title": "Trainer follow-along: Case 12A — Manual",
     "category": "TRAINER", "sort": 6},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "9:30 PM – 1:30 AM", "duration": 4.0,
     "title": "Plan cases 12A–13A",
     "category": "ASSIGNMENT", "sort": 7},
    {"day": 8, "week": "Week 1: Foundations of VIP", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 8},

    # Day 9
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Plan case 14A",
     "category": "ASSIGNMENT", "sort": 2},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "8:30 PM – 9:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 15A — Duplicate Manual",
     "category": "GENERAL", "sort": 3},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "9:00 PM – 11:00 PM", "duration": 2.0,
     "title": "Plan case 15A",
     "category": "ASSIGNMENT", "sort": 4},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "11:00 PM – 12:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "12:00 AM – 12:30 AM", "duration": 0.5,
     "title": "Watch training video: Case 16A — OV Adjusted Metal",
     "category": "GENERAL", "sort": 6},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "12:30 AM – 1:30 AM", "duration": 1.0,
     "title": "Plan case 16A",
     "category": "ASSIGNMENT", "sort": 7},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Review planned cases / feedback / WI review and management notes",
     "category": "TRAINER", "sort": 8},
    {"day": 9, "week": "Week 1: Foundations of VIP", "time_window": "2:00 AM – 3:00 AM", "duration": 1.0,
     "title": "Independent corrections / case notes cleanup",
     "category": "ASSIGNMENT", "sort": 9},

    # ── Week 2: Planning Set 2 ────────────────────────────────────────────────

    # Day 10 — mirrors Day 5 structure with Set B cases
    {"day": 10, "week": "Week 2: Planning Set 2", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 10, "week": "Week 2: Planning Set 2", "time_window": "6:30 PM – 7:30 PM", "duration": 1.0,
     "title": "Trainer follow-along: Case 1B — SUCCESS",
     "category": "TRAINER", "sort": 2},
    {"day": 10, "week": "Week 2: Planning Set 2", "time_window": "7:30 PM – 11:30 PM", "duration": 4.0,
     "title": "Plan cases 1B–2B",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 10, "week": "Week 2: Planning Set 2", "time_window": "11:30 PM – 12:30 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 10, "week": "Week 2: Planning Set 2", "time_window": "12:30 AM – 1:30 AM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 5},

    # Day 11 — mirrors Day 6
    {"day": 11, "week": "Week 2: Planning Set 2", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 11, "week": "Week 2: Planning Set 2", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 3B — SUCCESS",
     "category": "GENERAL", "sort": 2},
    {"day": 11, "week": "Week 2: Planning Set 2", "time_window": "7:00 PM – 12:00 AM", "duration": 5.0,
     "title": "Plan cases 3B–4B",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 11, "week": "Week 2: Planning Set 2", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 11, "week": "Week 2: Planning Set 2", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 5},

    # Day 12 — mirrors Day 7
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 5B — OV Adjusted",
     "category": "GENERAL", "sort": 2},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "7:00 PM – 10:00 PM", "duration": 3.0,
     "title": "Plan cases 5B–6B",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "10:00 PM – 11:00 PM", "duration": 1.0,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 4},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "11:00 PM – 12:00 AM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Trainer follow-along: Case 7B — Rejection",
     "category": "TRAINER", "sort": 6},
    {"day": 12, "week": "Week 2: Planning Set 2", "time_window": "1:00 AM – 2:00 AM", "duration": 1.0,
     "title": "Plan cases 7B–8B",
     "category": "ASSIGNMENT", "sort": 7},

    # Day 13 — mirrors Day 8
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Trainer follow-along: Case 9B — Rejection",
     "category": "TRAINER", "sort": 2},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "7:00 PM – 7:30 PM", "duration": 0.5,
     "title": "Plan cases 9B–11B",
     "category": "ASSIGNMENT", "sort": 3},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "7:30 PM – 8:00 PM", "duration": 0.5,
     "title": "Quick review / feedback / WI check",
     "category": "TRAINER", "sort": 4},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "8:00 PM – 9:00 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "9:00 PM – 9:30 PM", "duration": 0.5,
     "title": "Trainer follow-along: Case 12B — Manual",
     "category": "TRAINER", "sort": 6},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "9:30 PM – 1:30 AM", "duration": 4.0,
     "title": "Plan cases 12B–13B",
     "category": "ASSIGNMENT", "sort": 7},
    {"day": 13, "week": "Week 2: Planning Set 2", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 8},

    # Day 14 — sign-off day
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Plan case 14B",
     "category": "ASSIGNMENT", "sort": 2},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "8:30 PM – 9:00 PM", "duration": 0.5,
     "title": "Watch training video: Case 15B — Duplicate Manual",
     "category": "GENERAL", "sort": 3},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "9:00 PM – 10:30 PM", "duration": 1.5,
     "title": "Plan case 15B",
     "category": "ASSIGNMENT", "sort": 4},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "10:30 PM – 11:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 5},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "11:30 PM – 12:00 AM", "duration": 0.5,
     "title": "Watch training video: Case 16B — OV Adjusted Metal",
     "category": "GENERAL", "sort": 6},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "12:00 AM – 1:00 AM", "duration": 1.0,
     "title": "Plan case 16B",
     "category": "ASSIGNMENT", "sort": 7},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "1:00 AM – 1:30 AM", "duration": 0.5,
     "title": "Review planned cases / feedback / WI review",
     "category": "TRAINER", "sort": 8},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Final recap, completion signatures, and management feedback notes",
     "category": "TRAINER", "sort": 9},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "2:00 AM – 2:30 AM", "duration": 0.5,
     "title": "Independent LMS completion check / final upload",
     "category": "GENERAL", "sort": 10},
    {"day": 14, "week": "Week 2: Planning Set 2", "time_window": "2:30 AM – 3:00 AM", "duration": 0.5,
     "title": "Trainee final notes and action items for supervised live cases",
     "category": "ASSIGNMENT", "sort": 11},

    # ── Week 3: Live Cases (Supervised) ───────────────────────────────────────

    # Day 15
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Daily catch-up / questions",
     "category": "GENERAL", "sort": 1},
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:30 PM – 7:00 PM", "duration": 0.5,
     "title": "Mid-day check-in",
     "category": "GENERAL", "sort": 2},
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "7:00 PM – 9:00 PM", "duration": 2.0,
     "title": "Live cases — supervised production block 1",
     "category": "GENERAL", "sort": 3},
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "9:00 PM – 10:00 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 4},
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "10:00 PM – 1:30 AM", "duration": 3.5,
     "title": "Live cases — supervised production block 2",
     "category": "GENERAL", "sort": 5},
    {"day": 15, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "End-of-day check-in",
     "category": "GENERAL", "sort": 6},

    # Day 16
    {"day": 16, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Mid-day check-in / trainee status check",
     "category": "GENERAL", "sort": 1},
    {"day": 16, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Live cases — supervised production block 1",
     "category": "GENERAL", "sort": 2},
    {"day": 16, "week": "Week 3: Live Cases (Supervised)", "time_window": "8:30 PM – 9:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 3},
    {"day": 16, "week": "Week 3: Live Cases (Supervised)", "time_window": "9:30 PM – 1:00 AM", "duration": 3.5,
     "title": "Live cases — supervised production block 2",
     "category": "GENERAL", "sort": 4},
    {"day": 16, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:00 AM – 1:30 AM", "duration": 0.5,
     "title": "End-of-day check-in",
     "category": "GENERAL", "sort": 5},

    # Day 17
    {"day": 17, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Mid-day check-in / trainee status check",
     "category": "GENERAL", "sort": 1},
    {"day": 17, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Live cases — supervised production block 1",
     "category": "GENERAL", "sort": 2},
    {"day": 17, "week": "Week 3: Live Cases (Supervised)", "time_window": "8:30 PM – 9:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 3},
    {"day": 17, "week": "Week 3: Live Cases (Supervised)", "time_window": "9:30 PM – 1:00 AM", "duration": 3.5,
     "title": "Live cases — supervised production block 2",
     "category": "GENERAL", "sort": 4},
    {"day": 17, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:00 AM – 1:30 AM", "duration": 0.5,
     "title": "End-of-day check-in",
     "category": "GENERAL", "sort": 5},

    # Day 18
    {"day": 18, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Mid-day check-in / trainee status check",
     "category": "GENERAL", "sort": 1},
    {"day": 18, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Live cases — supervised production block 1",
     "category": "GENERAL", "sort": 2},
    {"day": 18, "week": "Week 3: Live Cases (Supervised)", "time_window": "8:30 PM – 9:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 3},
    {"day": 18, "week": "Week 3: Live Cases (Supervised)", "time_window": "9:30 PM – 1:00 AM", "duration": 3.5,
     "title": "Live cases — supervised production block 2",
     "category": "GENERAL", "sort": 4},
    {"day": 18, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:00 AM – 1:30 AM", "duration": 0.5,
     "title": "End-of-day check-in",
     "category": "GENERAL", "sort": 5},

    # Day 19
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:00 PM – 6:30 PM", "duration": 0.5,
     "title": "Mid-day check-in / trainee status check",
     "category": "GENERAL", "sort": 1},
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "6:30 PM – 8:30 PM", "duration": 2.0,
     "title": "Live cases — supervised production block 1",
     "category": "GENERAL", "sort": 2},
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "8:30 PM – 9:30 PM", "duration": 1.0,
     "title": "Meal Break",
     "category": "BREAK", "sort": 3},
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "9:30 PM – 1:00 AM", "duration": 3.5,
     "title": "Live cases — supervised production block 2",
     "category": "GENERAL", "sort": 4},
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:00 AM – 1:30 AM", "duration": 0.5,
     "title": "End-of-day check-in",
     "category": "GENERAL", "sort": 5},
    {"day": 19, "week": "Week 3: Live Cases (Supervised)", "time_window": "1:30 AM – 2:00 AM", "duration": 0.5,
     "title": "Feedback to Management",
     "category": "LEADS", "sort": 6},
]

